### ISSUE TITLE
关于法律责任承担

### ISSUE THREAD

**Issue by liujiahua123123** [lc6a/spring_mirai#15]
您好，

十分感谢使用Mirai框架作为底层框架。

但请注意 Mirai作为一个学习性项目，没有能力也没有义务承担任何可能的法律责任，烦请您修改README

谨代表 Mirai开发维护, 社区成员 在 2021年6月19日声明 我们不接受承担任何由 spring_mirai 项目带来的法律责任。

**Comment by lc6a** [comment]
好的，稍后修改
